// Generated by scripts/generate-rollout-deployments.ts. Do not edit addresses or blocks.
export const CTPublisherV6Abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "directory",
        type: "address",
        internalType: "contract IJBDirectory"
      },
      {
        name: "permissions",
        type: "address",
        internalType: "contract IJBPermissions"
      },
      {
        name: "feeProjectId",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "permit2",
        type: "address",
        internalType: "contract IPermit2"
      },
      {
        name: "trustedForwarder",
        type: "address",
        internalType: "address"
      }
    ],
    stateMutability: "nonpayable"
  },
  {
    type: "function",
    name: "DIRECTORY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IJBDirectory"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "FEE_DIVISOR",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "FEE_PROJECT_ID",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "PERMISSIONS",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IJBPermissions"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "PERMIT2",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IPermit2"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "allowanceFor",
    inputs: [
      {
        name: "hook",
        type: "address",
        internalType: "address"
      },
      {
        name: "category",
        type: "uint256",
        internalType: "uint256"
      }
    ],
    outputs: [
      {
        name: "minimumPrice",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "minimumTotalSupply",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "maximumTotalSupply",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "maximumSplitPercent",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "allowedAddresses",
        type: "address[]",
        internalType: "address[]"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "configurePostingCriteriaFor",
    inputs: [
      {
        name: "allowedPosts",
        type: "tuple[]",
        internalType: "struct CTAllowedPost[]",
        components: [
          {
            name: "hook",
            type: "address",
            internalType: "address"
          },
          {
            name: "category",
            type: "uint24",
            internalType: "uint24"
          },
          {
            name: "minimumPrice",
            type: "uint104",
            internalType: "uint104"
          },
          {
            name: "minimumTotalSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "maximumTotalSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "maximumSplitPercent",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "allowedAddresses",
            type: "address[]",
            internalType: "address[]"
          }
        ]
      }
    ],
    outputs: [],
    stateMutability: "nonpayable"
  },
  {
    type: "function",
    name: "isTrustedForwarder",
    inputs: [
      {
        name: "forwarder",
        type: "address",
        internalType: "address"
      }
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "mintFrom",
    inputs: [
      {
        name: "hook",
        type: "address",
        internalType: "contract IJB721TiersHook"
      },
      {
        name: "posts",
        type: "tuple[]",
        internalType: "struct CTPost[]",
        components: [
          {
            name: "encodedIpfsUri",
            type: "bytes32",
            internalType: "bytes32"
          },
          {
            name: "totalSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "price",
            type: "uint104",
            internalType: "uint104"
          },
          {
            name: "category",
            type: "uint24",
            internalType: "uint24"
          },
          {
            name: "splitPercent",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "splits",
            type: "tuple[]",
            internalType: "struct JBSplit[]",
            components: [
              {
                name: "percent",
                type: "uint32",
                internalType: "uint32"
              },
              {
                name: "projectId",
                type: "uint64",
                internalType: "uint64"
              },
              {
                name: "beneficiary",
                type: "address",
                internalType: "address payable"
              },
              {
                name: "preferAddToBalance",
                type: "bool",
                internalType: "bool"
              },
              {
                name: "lockedUntil",
                type: "uint48",
                internalType: "uint48"
              },
              {
                name: "hook",
                type: "address",
                internalType: "contract IJBSplitHook"
              }
            ]
          }
        ]
      },
      {
        name: "token",
        type: "address",
        internalType: "address"
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "nftBeneficiary",
        type: "address",
        internalType: "address"
      },
      {
        name: "feeBeneficiary",
        type: "address",
        internalType: "address"
      },
      {
        name: "additionalPayMetadata",
        type: "bytes",
        internalType: "bytes"
      }
    ],
    outputs: [],
    stateMutability: "payable"
  },
  {
    type: "function",
    name: "tierIdForEncodedIpfsUriOf",
    inputs: [
      {
        name: "hook",
        type: "address",
        internalType: "address"
      },
      {
        name: "encodedIpfsUri",
        type: "bytes32",
        internalType: "bytes32"
      }
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "tiersFor",
    inputs: [
      {
        name: "hook",
        type: "address",
        internalType: "address"
      },
      {
        name: "encodedIpfsUris",
        type: "bytes32[]",
        internalType: "bytes32[]"
      }
    ],
    outputs: [
      {
        name: "tiers",
        type: "tuple[]",
        internalType: "struct JB721Tier[]",
        components: [
          {
            name: "id",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "price",
            type: "uint104",
            internalType: "uint104"
          },
          {
            name: "remainingSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "initialSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "votingUnits",
            type: "uint104",
            internalType: "uint104"
          },
          {
            name: "reserveFrequency",
            type: "uint16",
            internalType: "uint16"
          },
          {
            name: "reserveBeneficiary",
            type: "address",
            internalType: "address"
          },
          {
            name: "encodedIpfsUri",
            type: "bytes32",
            internalType: "bytes32"
          },
          {
            name: "category",
            type: "uint24",
            internalType: "uint24"
          },
          {
            name: "discountPercent",
            type: "uint8",
            internalType: "uint8"
          },
          {
            name: "flags",
            type: "tuple",
            internalType: "struct JB721TierFlags",
            components: [
              {
                name: "allowOwnerMint",
                type: "bool",
                internalType: "bool"
              },
              {
                name: "transfersPausable",
                type: "bool",
                internalType: "bool"
              },
              {
                name: "cantBeRemoved",
                type: "bool",
                internalType: "bool"
              },
              {
                name: "cantIncreaseDiscountPercent",
                type: "bool",
                internalType: "bool"
              },
              {
                name: "cantBuyWithCredits",
                type: "bool",
                internalType: "bool"
              }
            ]
          },
          {
            name: "splitPercent",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "resolvedUri",
            type: "string",
            internalType: "string"
          }
        ]
      }
    ],
    stateMutability: "view"
  },
  {
    type: "function",
    name: "trustedForwarder",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address"
      }
    ],
    stateMutability: "view"
  },
  {
    type: "event",
    name: "ConfigurePostingCriteria",
    inputs: [
      {
        name: "hook",
        type: "address",
        indexed: true,
        internalType: "address"
      },
      {
        name: "allowedPost",
        type: "tuple",
        indexed: false,
        internalType: "struct CTAllowedPost",
        components: [
          {
            name: "hook",
            type: "address",
            internalType: "address"
          },
          {
            name: "category",
            type: "uint24",
            internalType: "uint24"
          },
          {
            name: "minimumPrice",
            type: "uint104",
            internalType: "uint104"
          },
          {
            name: "minimumTotalSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "maximumTotalSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "maximumSplitPercent",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "allowedAddresses",
            type: "address[]",
            internalType: "address[]"
          }
        ]
      },
      {
        name: "caller",
        type: "address",
        indexed: false,
        internalType: "address"
      }
    ],
    anonymous: false
  },
  {
    type: "event",
    name: "Mint",
    inputs: [
      {
        name: "projectId",
        type: "uint256",
        indexed: true,
        internalType: "uint256"
      },
      {
        name: "hook",
        type: "address",
        indexed: true,
        internalType: "contract IJB721TiersHook"
      },
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address"
      },
      {
        name: "nftBeneficiary",
        type: "address",
        indexed: true,
        internalType: "address"
      },
      {
        name: "feeBeneficiary",
        type: "address",
        indexed: false,
        internalType: "address"
      },
      {
        name: "posts",
        type: "tuple[]",
        indexed: false,
        internalType: "struct CTPost[]",
        components: [
          {
            name: "encodedIpfsUri",
            type: "bytes32",
            internalType: "bytes32"
          },
          {
            name: "totalSupply",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "price",
            type: "uint104",
            internalType: "uint104"
          },
          {
            name: "category",
            type: "uint24",
            internalType: "uint24"
          },
          {
            name: "splitPercent",
            type: "uint32",
            internalType: "uint32"
          },
          {
            name: "splits",
            type: "tuple[]",
            internalType: "struct JBSplit[]",
            components: [
              {
                name: "percent",
                type: "uint32",
                internalType: "uint32"
              },
              {
                name: "projectId",
                type: "uint64",
                internalType: "uint64"
              },
              {
                name: "beneficiary",
                type: "address",
                internalType: "address payable"
              },
              {
                name: "preferAddToBalance",
                type: "bool",
                internalType: "bool"
              },
              {
                name: "lockedUntil",
                type: "uint48",
                internalType: "uint48"
              },
              {
                name: "hook",
                type: "address",
                internalType: "contract IJBSplitHook"
              }
            ]
          }
        ]
      },
      {
        name: "postValue",
        type: "uint256",
        indexed: false,
        internalType: "uint256"
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256"
      },
      {
        name: "caller",
        type: "address",
        indexed: false,
        internalType: "address"
      }
    ],
    anonymous: false
  },
  {
    type: "event",
    name: "Permit2AllowanceFailed",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address"
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address"
      },
      {
        name: "reason",
        type: "bytes",
        indexed: false,
        internalType: "bytes"
      }
    ],
    anonymous: false
  },
  {
    type: "error",
    name: "CTPublisher_DuplicatePayMetadata",
    inputs: [
      {
        name: "payMetadataId",
        type: "bytes4",
        internalType: "bytes4"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_DuplicatePost",
    inputs: [
      {
        name: "encodedIpfsUri",
        type: "bytes32",
        internalType: "bytes32"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_EmptyEncodedIpfsUri",
    inputs: [
      {
        name: "postIndex",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_FeePaymentFailed",
    inputs: [
      {
        name: "feeAmount",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_InsufficientEthSent",
    inputs: [
      {
        name: "expected",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "sent",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_InsufficientPayment",
    inputs: [
      {
        name: "expected",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "sent",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_InvalidFeeBeneficiary",
    inputs: []
  },
  {
    type: "error",
    name: "CTPublisher_InvalidPaymentTokenContext",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address"
      },
      {
        name: "tokenCurrency",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "tokenDecimals",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "pricingCurrency",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "pricingDecimals",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_MaxTotalSupplyLessThanMin",
    inputs: [
      {
        name: "min",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "max",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_MintNotDelivered",
    inputs: [
      {
        name: "hook",
        type: "address",
        internalType: "address"
      },
      {
        name: "beneficiary",
        type: "address",
        internalType: "address"
      },
      {
        name: "expectedBalance",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "actualBalance",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_MsgValueNotAllowed",
    inputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_NativeTokenAmountMismatch",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "msgValue",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_NoPosts",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_NotInAllowList",
    inputs: [
      {
        name: "addr",
        type: "address",
        internalType: "address"
      },
      {
        name: "allowedAddresses",
        type: "address[]",
        internalType: "address[]"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_OverflowAlert",
    inputs: [
      {
        name: "value",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "limit",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_PermitAllowanceNotEnough",
    inputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "allowance",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_PriceFeedUnavailable",
    inputs: [
      {
        name: "paymentCurrency",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "pricingCurrency",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_PriceTooSmall",
    inputs: [
      {
        name: "price",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "minimumPrice",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_ReentrantTokenTransfer",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_SplitPercentExceedsMaximum",
    inputs: [
      {
        name: "splitPercent",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "maximumSplitPercent",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_TemporaryAllowanceNotConsumed",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address"
      },
      {
        name: "spender",
        type: "address",
        internalType: "address"
      },
      {
        name: "allowance",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_TotalSupplyTooBig",
    inputs: [
      {
        name: "totalSupply",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "maximumTotalSupply",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_TotalSupplyTooSmall",
    inputs: [
      {
        name: "totalSupply",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "minimumTotalSupply",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_UnauthorizedToPostInCategory",
    inputs: [
      {
        name: "hook",
        type: "address",
        internalType: "address"
      },
      {
        name: "category",
        type: "uint24",
        internalType: "uint24"
      }
    ]
  },
  {
    type: "error",
    name: "CTPublisher_ZeroTotalSupply",
    inputs: [
      {
        name: "hook",
        type: "address",
        internalType: "address"
      },
      {
        name: "category",
        type: "uint24",
        internalType: "uint24"
      }
    ]
  },
  {
    type: "error",
    name: "JBMetadataResolver_DataNotPadded",
    inputs: [
      {
        name: "dataLength",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "JBMetadataResolver_MetadataTooLong",
    inputs: [
      {
        name: "offset",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "maxOffset",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "JBMetadataResolver_MetadataTooShort",
    inputs: [
      {
        name: "metadataLength",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "minMetadataLength",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "JBPermissioned_Unauthorized",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address"
      },
      {
        name: "sender",
        type: "address",
        internalType: "address"
      },
      {
        name: "projectId",
        type: "uint256",
        internalType: "uint256"
      },
      {
        name: "permissionId",
        type: "uint256",
        internalType: "uint256"
      }
    ]
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address"
      }
    ]
  }
] as const;
