import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Abi } from "viem";

// Regenerate after canonical deployment artifacts land; no RPC, proposal, or
// deterministic future address is accepted as evidence of a deployment.
const args = process.argv.slice(2);
const option = (name: string) => {
  const index = args.indexOf(name);
  if (index === -1) return undefined;
  if (!args[index + 1] || args[index + 1]!.startsWith("--")) {
    throw new Error(`Missing value for ${name}`);
  }
  return args[index + 1]!;
};
const root = resolve(option("--deployments") ?? "../deploy-all-v6/deployments");
const ref = option("--ref");
const repository = dirname(root);
const git = (...gitArgs: string[]) =>
  execFileSync("git", ["-C", repository, ...gitArgs], { encoding: "utf8" });
const revision = ref ? git("rev-parse", `${ref}^{commit}`).trim() : undefined;
const read = (path: string) =>
  revision ? git("show", `${revision}:deployments/${path}`) : readFileSync(resolve(root, path), "utf8");
const paths = revision
  ? git("ls-tree", "-r", "--name-only", revision, "deployments").trim().split("\n").map((path) => path.replace(/^deployments\//, ""))
  : readdirSync(root, { withFileTypes: true }).filter((entry) => entry.isDirectory()).flatMap((entry) => readdirSync(resolve(root, entry.name)).map((file) => `${entry.name}/${file}`));

const chains = {
  ethereum: { name: "ethereum", id: 1, testnet: false },
  arbitrum: { name: "arbitrum", id: 42161, testnet: false },
  base: { name: "base", id: 8453, testnet: false },
  optimism: { name: "optimism", id: 10, testnet: false },
  sepolia: { name: "ethereumSepolia", id: 11155111, testnet: true },
  arbitrum_sepolia: { name: "arbitrumSepolia", id: 421614, testnet: true },
  base_sepolia: { name: "baseSepolia", id: 84532, testnet: true },
  optimism_sepolia: { name: "optimismSepolia", id: 11155420, testnet: true },
} as const;
const contracts = ["JBBuybackHook", "JBRouterTerminal", "JBRouterTerminalGateway", "JBRatioPriceFeed", "JBUniswapV4Hook", "CTPublisher"] as const;
type Contract = typeof contracts[number];
type Artifact = {
  address: `0x${string}`;
  chainId: string;
  gitCommit?: string;
  abi: Abi;
  receipt?: { blockNumber?: string; status?: string; transactionHash?: `0x${string}` };
};
const artifacts = new Map<Contract, Artifact[]>();
const deployments = paths.sort().flatMap((path) => {
  const [directory, file] = path.split("/");
  const chain = chains[directory as keyof typeof chains];
  if (!chain || !file) return [];
  const contract = contracts.find((name) => file === `${name}.json` || new RegExp(`^${name}_deprecated\\d*\\.json$`).test(file));
  if (!contract) return [];
  const artifact = JSON.parse(read(path)) as Artifact;
  const block = artifact.receipt?.blockNumber;
  const startBlock = block === undefined ? NaN : Number(BigInt(block));
  if (!Number.isSafeInteger(startBlock) || startBlock <= 0 || artifact.receipt?.status !== "0x1" || !artifact.receipt.transactionHash) {
    throw new Error(`Missing successful deployment receipt: ${path}`);
  }
  if (!/^0x[0-9a-f]{40}$/i.test(artifact.address) || Number(BigInt(artifact.chainId)) !== chain.id) {
    throw new Error(`Invalid deployment identity: ${path}`);
  }
  artifacts.set(contract, [...(artifacts.get(contract) ?? []), artifact]);
  const packageVersion = artifact.gitCommit?.match(/@(\d+\.\d+\.\d+)$/)?.[1] ?? null;
  return [{
    contract, chain: chain.name, chainId: chain.id, testnet: chain.testnet,
    address: artifact.address.toLowerCase(), startBlock,
    // "current" names the canonical artifact, not a claim that every project
    // selected it. Previous generations remain indexable after deprecation.
    generation: file === `${contract}.json` ? "current" : file === `${contract}_deprecated.json` ? "v1" : "previous",
    packageVersion, artifact: `deployments/${path}`, transactionHash: artifact.receipt.transactionHash,
  }];
});
if (deployments.length === 0) throw new Error("No deployment receipts found");
const header = "// Generated by scripts/generate-rollout-deployments.ts. Do not edit addresses or blocks.\n";
const outputs: [string, string][] = [["src/constants/rolloutDeployments.ts", `${header}export const ROLLOUT_DEPLOYMENTS = ${JSON.stringify({ source: "Bananapus/deploy-all-v6", revision: revision ?? null, deployments }, null, 2)} as const;\n`]];
for (const contract of ["JBBuybackHook", "JBRouterTerminal", "JBRouterTerminalGateway", "CTPublisher"] as const) {
  const versions = artifacts.get(contract);
  if (!versions?.length) throw new Error(`Missing ABI source for ${contract}`);
  const versionParts = (artifact: Artifact) => (artifact.gitCommit?.match(/@(\d+\.\d+\.\d+)$/)?.[1] ?? "0.0.0").split(".").map(Number);
  versions.sort((a, b) => {
    const left = versionParts(a), right = versionParts(b);
    for (let i = 0; i < 3; i++) if (left[i] !== right[i]) return right[i]! - left[i]!;
    return 0;
  });
  // Preserve the existing TypeScript ABI style so diffs show changes to the ABI.
  const abi = JSON.stringify(versions[0]!.abi, null, 2).replace(/^([ \t]*)"([A-Za-z_$][\w$]*)":/gm, "$1$2:");
  outputs.push([`abis/${contract}V6Abi.ts`, `${header}export const ${contract}V6Abi = ${abi} as const;\n`]);
}
// Validate every source before replacing any generated output.
for (const [path, contents] of outputs) writeFileSync(path, contents);
console.log(`Generated ${deployments.length} receipt-backed deployments and 4 ABIs`);
